### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by zgzxy001** [rvl-lab-utoronto/video_similarity_search#77]
Hi, thank you for the great work! May I ask your GPU type and per-training time on UCF and Kinetics400 datasets? Thanks!

**Comment by Salarios77** [comment]
Hi, thank you! Yes, the details of the training are in Appendix Section B of the paper. In particular, "UCF101 training was done on 2 GPUs with a batch size of 16 samples per GPU, and lasted for 600 epochs. Kinetics400 training was done on 8 GPUs with a batch size of 13 samples per GPU, and lasted for 340 epochs." Using these settings with Nvidia P100 GPUs, UCF101 pretraining takes approximately 3-5 days, and Kinetics400 pretraining takes approximately 2-3 weeks.
